version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=leantime
      - MYSQL_USER=admin
      - MYSQL_PASSWORD
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
  web:
    image: leantime/leantime:latest
    container_name: leantime
    environment:
      - LEAN_DB_HOST=db
      - LEAN_DB_USER=admin
      - LEAN_DB_PASSWORD
      - LEAN_DB_DATABASE=leantime
    depends_on:
      - db
    networks:
      - caddy
      - default
    labels:
      caddy: leantime.semudando.com.br
      caddy.reverse_proxy: "{{upstreams}}"
volumes:
  db_data: {}

networks:
  caddy:
    external: true