version: "3.8"

services:
  configurator:
    image: semudando/erpnext:1.1.0
    restart: "no"
    entrypoint:
      - bash
      - -c
    command:
      - >
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_SOCKETIO";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis:6379
      REDIS_QUEUE: redis:6379
      REDIS_SOCKETIO: redis:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites

  backend:
    image: semudando/erpnext:1.1.0
    volumes:
      - sites:/home/frappe/frappe-bench/sites

  frontend:
    image: semudando/erpnext:1.1.0
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: semudando
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    labels:
      caddy: erpnext.semudando.com.br
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - default
      - caddy

  queue-default:
    image: semudando/erpnext:1.1.0
    command: bench worker --queue default
    volumes:
      - sites:/home/frappe/frappe-bench/sites

  queue-long:
    image: semudando/erpnext:1.1.0
    command: bench worker --queue long
    volumes:
      - sites:/home/frappe/frappe-bench/sites

  queue-short:
    image: semudando/erpnext:1.1.0
    command: bench worker --queue short
    volumes:
      - sites:/home/frappe/frappe-bench/sites
  scheduler:
    image: semudando/erpnext:1.1.0
    command: bench schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites

  websocket:
    image: frappe/erpnext:v14
    volumes:
      - sites:/home/frappe/frappe-bench/sites

  redis:
    image: redis:6.2-alpine


  backup:
    image: b3vis/borgmatic
    volumes:
      - sites:/data/sites:ro
      - db-data:/data/db-data:ro
      - ssh:/root/.ssh/:ro
    environment:
      - BORG_PASSPHRASE
    configs:
      - source: borgmatic-config-erpnext
        target: /etc/borgmatic.d/config.yaml
      - source: borgmatic-crontab-erpnext
        target: /etc/borgmatic.d/crontab.txt

  db:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      - MARIADB_ROOT_PASSWORD
    volumes:
      - db-data:/var/lib/mysql

configs:
  borgmatic-config-erpnext:
    external: true
  borgmatic-crontab-erpnext:
    external: true

volumes:
  db-data:
  sites:
  ssh:
    external: true

networks:
  caddy:
    external: true