version: "3.8"

services:

  linkstack:
    image: linkstackorg/linkstack
    volumes:
      - linkstack:/htdocs
    environment:
      - SERVER_ADMIN=admin@semudando.com.br
      - HTTPS_SERVER_NAME=links.semudando.com.br
      - HTTP_SERVER_NAME=links.semudando.com.br
      - PHP_MEMORY_LIMIT=512M
      - UPLOAD_MAX_FILESIZE=512M
      - LOG_LEVEL=trace8
    restart: always
    networks:
      - caddy
    labels:
      caddy: links.semudando.com.br
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.header.Content-Security-Policy: "upgrade-insecure-requests"

  backup:
    image: b3vis/borgmatic
    volumes:
      - linkstack:/data/linkstack
      - ssh:/root/.ssh/
    environment:
      - BORG_PASSPHRASE
      - BACKUP_CRON=0 1 * * * # Remove when https://github.com/borgmatic-collective/docker-borgmatic/issues/375 is fixed
    configs:
      - source: borgmatic-config-linkstack-semudando
        target: /etc/borgmatic.d/config.yaml

configs:
  borgmatic-config-linkstack-semudando:
    external: true

volumes:
  linkstack:
  ssh:
    external: true

networks:
  caddy:
    external: true


