version: "3.8"

services:

  linkstack:
    image: linkstackorg/linkstack
    volumes:
      - linkstack:/htdocs
    environment:
      - SERVER_ADMIN=admin@semudando.com.br
      - HTTPS_SERVER_NAME=links.semudando.com.br
      - HTTP_SERVER_NAME=links.semudando.com.br
      - PHP_MEMORY_LIMIT=512M
      - UPLOAD_MAX_FILESIZE=512M
    restart: always
    networks:
      - caddy
    labels:
      caddy: links.semudando.com.br
      caddy.reverse_proxy: "{{upstreams https}}"

volumes:
  linkstack:

networks:
  caddy:
    external: true


