version: "3.8"

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB=singlelink
      - POSTGRES_USER=singlelink

  singlelink:
    image: leocolman/singlelink-docker:1.0.0
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=singlelink
      - PGUSER=singlelink
      - PGPASSWORD

      - META_TITLE=Se Mudando
      - META_DESC=Portal de links do Instituto Se Mudando
      - BRANDING=false

      - SECRET
      - PASSWORD
    networks:
      - caddy
      - default
    labels:
      caddy: links.semudando.com.br
      caddy.reverse_proxy: "{{upstreams 3000}}"

  borgmatic:
    image: b3vis/borgmatic
    volumes:
      - postgres:/data:ro
      - ssh:/root/.ssh/
    environment:
      - BORG_PASSPHRASE
    configs:
      - source: borgmatic-config-singlelink
        target: /etc/borgmatic.d/config.yaml
      - source: borgmatic-crontab-singlelink
        target: /etc/borgmatic.d/crontab.txt

volumes:
  postgres: {}
  ssh:
    external: true

configs:
  borgmatic-config-singlelink:
    external: true
  borgmatic-crontab-singlelink:
    external: true

networks:
  caddy:
    external: true


