version: "3.8"

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: singlelink
      POSTGRES_USER: singlelink
      POSTGRES_PASSWORD: secret

  borgmatic:
    image: b3vis/borgmatic
    volumes:
      - postgres:/data:ro
    environment:
      - BORG_PASSPHRASE
    configs:
      - source: borgmatic-config-singlelink
        target: /etc/borgmatic/config.yaml
      - source: borgmatic-crontab-singlelink
        target: /etc/borgmatic/crontab.txt
    secrets:
      - source: borgmatic-ssh-singlelink
        target: /root/.ssh/id_rsa

  singlelink:
    image: leocolman/singlelink-docker:1.0.0
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: singlelink
      PGUSER: singlelink
      PGPASSWORD: secret

      META_TITLE: Singlelink
      META_DESC: My Singlelink Docker Instance
      META_IMG:
      BRANDING: "true"

      SECRET: jwt_secret
      PASSWORD: singlelink-password

volumes:
  postgres: {}

configs:
  borgmatic-config-singlelink:
    external: true
  borgmatic-crontab-singlelink:
    external: true

secrets:
  borgmatic-ssh-singlelink:
    external: true
