version: "3.8"

services:
  postgres:
    env_file: configuration.env
    image: postgres
    expose:
      - 5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
  backup:
    image: b3vis/borgmatic
    volumes:
      - ./data/:/data:ro
      - ./borgmatic:/etc/borgmatic.d/
      - ./borgmatic/ssh:/root/.ssh
    environment:
#      BORG_PASSPHRASE: abcde
  singlelink:
    env_file: configuration.env
    build: dockerfile
    depends_on:
      - postgres
    expose:
      - 3000
    labels:
      caddy: links.semudando.com.br
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - caddy
      - default

networks:
  caddy:
    external: true