version: "3.8"

services:
  redmine:
    image: redmine:5.0.5
    environment:
      - REDMINE_DB_MYSQL=db
      - REDMINE_DB_PASSWORD
      - REDMINE_SECRET_KEY_BASE
    networks:
      - caddy
      - default
    volumes:
      - redmine:/usr/src/redmine
    labels:
      caddy: projetos.semudando.com.br
      caddy.reverse_proxy: "{{upstreams 3000}}"
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=redmine
    volumes:
      - database:/var/lib/mysql

  backup:
    image: b3vis/borgmatic
    volumes:
      - redmine:/data/redmine:ro
      - database:/data/database:ro
      - ssh:/root/.ssh/:ro
    environment:
      - BORG_PASSPHRASE
    configs:
      - source: borgmatic-config-redmine
        target: /etc/borgmatic.d/config.yaml
      - source: borgmatic-crontab-redmine
        target: /etc/borgmatic.d/crontab.txt


configs:
  borgmatic-config-redmine:
    external: true
  borgmatic-crontab-redmine:
    external: true

volumes:
  database: {}
  redmine: {}
  ssh:
    external: true

networks:
  caddy:
    external: true