version: "3.8"

services:
  mariadb:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file: db.env
    volumes:
      - database:/var/lib/mysql
  redis:
    image: redis:alpine

  nextcloud:
    image: nextcloud:stable
    networks:
      - caddy
      - default
    env_file:
      - nextcloud.env
      - db.env
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - mariadb
      - redis
    labels:
      caddy: "nextcloud.semudando.com.br"
      caddy.reverse_proxy: "{{upstreams}}"
      caddy.header: /*
      caddy.header.Strict-Transport-Security: "max-age=15552000"
      caddy.rewrite_0: /.well-known/carddav /remote.php/dav
      caddy.rewrite_1: /.well-known/caldav /remote.php/dav


  collabora:
    image: collabora/code
    restart: always
    networks:
      - caddy
    cap_add:
      - MKNOD
    env_file: collabora.env
    labels:
      caddy: collabora.semudando.com.br
      caddy.reverse_proxy: "{{upstreams 9980}}"

  backup:
    image: b3vis/borgmatic
    volumes:
      - database:/data/database:ro
      - nextcloud:/data/nextcloud:ro
    environment:
      - BORG_PASSPHRASE
    configs:
      - source: borgmatic-config-nextcloud
        target: /etc/borgmatic/config.yaml
      - source: borgmatic-crontab-nextcloud
        target: /etc/borgmatic/crontab.txt
    secrets:
      - source: borgmatic-ssh-nextcloud
        target: /root/.ssh/id_rsa
        mode: 0600


configs:
  borgmatic-config-nextcloud:
    external: true
  borgmatic-crontab-nextcloud:
    external: true

secrets:
  borgmatic-ssh-nextcloud:
    external: true

networks:
  caddy:
    external: true

volumes:
  database:
  nextcloud: