version: "3.8"

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:6.13.0
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    environment:
      - PORT=3000
      - ROOT_URL=https://chat.semudando.com.br
      - MONGO_URL=mongodb://mongo:27017/rocketchat?directConnection=true
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local?replSet=rs0&directConnection=true
      - OVERWRITE_SETTING_Accounts_TwoFactorAuthentication_Enabled=false
      - OVERWRITE_SETTING_Accounts_TwoFactorAuthentication_Enforce_Password_Fallback=false
    depends_on:
      - mongo
    networks:
      - default
      - caddy
    labels:
      caddy: chat.semudando.com.br
      caddy.reverse_proxy: "{{upstreams 3000}}"

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
    command: mongod --oplogSize 128 --replSet rs0

  borgmatic:
    image: b3vis/borgmatic
    volumes:
      - mongodb:/data
      - ssh:/root/.ssh/
    environment:
      - BORG_PASSPHRASE
    configs:
      - source: borgmatic-config-rocketchat
        target: /etc/borgmatic.d/config.yaml

configs:
  borgmatic-config-rocketchat:
    external: true

volumes:
  mongodb: {}
  ssh:
    external: true

networks:
  caddy:
    external: true