version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress:/var/www/html
    networks:
      - default
      - caddy
    environment:
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_PASSWORD
    labels:
      caddy: wordpress.semudando.com.br
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true

volumes:
  mysql:
  wordpress: