version: '3.3'

services:
  database:
    image: mariadb:lts
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=firefly
      - MYSQL_DATABASE=firefly
      - MYSQL_PASSWORD
    volumes:
      - database

  app:
    image: fireflyiii/core:latest
    volumes:
      - firefly
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - SITE_OWNER=admin@semudando.com.br
      - DEFAULT_LANGUAGE=pt_BR
      - DEFAULT_LOCALE=equal
      - TZ=America/Sao_Paulo
      - TRUSTED_PROXIES=**
      - LOG_CHANNEL=stack
      - APP_LOG_LEVEL=notice
      - AUDIT_LOG_LEVEL-emergency
      - DB_CONNECCTION=mysql
      - DB_HOST=database
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - APP_URL=https://firefly.semudando.com.br
      - APP_KEY
      - DB_PASSWORD
    depends_on:
      - database
    labels:
      caddy: firefly.semudando.com.br
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - caddy
      - default

  importer:
    image: fireflyiii/data-importer:latest
    depends_on:
      - app
    environment:
      - FIREFLY_III_URL=https://firefly.semudando.com.br
      - VANITY_URL=https://firefly.semudando.com.br
      - TZ=America/Sao_Paulo
      - TRUSTED_PROXIES=**
      - FIREFLY_III_ACCESS_TOKEN
      - FIREFLY_III_CLIENT_ID
    networks:
      - caddy
      - default
    labels:
      caddy: importer.firefly.semudando.com.br
      caddy.reverse_proxy: "{{upstreams 8080}}"

  cron:
    image: alpine
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/$STATIC_CRON_TOKEN\" | crontab - && crond -f -L /dev/stdout"
    environment:
      - STATIC_CRON_TOKEN
  
  backup:
    image: b3vis/borgmatic
    volumes:
      - database
      - firefly
      - ssh:/root/.ssh/
    environment:
      - BORG_PASSPHRASE
      - BACKUP_CRON=0 1 * * * # Remove when https://github.com/borgmatic-collective/docker-borgmatic/issues/375 is fixed
    configs:
      - source: borgmatic-config-firefly
        target: /etc/borgmatic.d/config.yaml

configs:
  borgmatic-config-firefly:
    external: true

volumes:
  firefly:
  database:
  ssh:
    external: true

networks:
  caddy:
    external: true
