services:
  uptime-kuma:
    image: louislam/uptime-kuma:1-alpine
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - caddy
    restart: unless-stopped
    labels:
      caddy: kuma.semudando.com.br
      caddy.reverse_proxy: "{{upstreams 3001}}"

volumes:
  uptime-kuma-data:

networks:
  caddy:
    external: true