version: "3.3"

services:
  
  backup:
    image: b3vis/borgmatic
    volumes:
      - postgres:/data/postgres
      - uploads:/data/uploads
      - ssh:/root/.ssh/
    environment:
      - BORG_PASSPHRASE
      - BACKUP_CRON=0 1 * * * # Remove when https://github.com/borgmatic-collective/docker-borgmatic/issues/375 is fixed
    configs:
      - source: borgmatic-config-formbricks-semudando
        target: /etc/borgmatic.d/config.yaml
  
  postgres:
    image: pgvector/pgvector:pg17
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  
  formbricks:
    restart: always
    image: ghcr.io/formbricks/formbricks:latest
    depends_on:
      - postgres
    labels:
      caddy: "forms.semudando.com.br"
      caddy.reverse_proxy: "{{upstreams 3000}}"
    volumes:
      - uploads:/home/nextjs/apps/web/uploads/
    environment:
      - NEXTAUTH_SECRET
      - ENCRYPTION_KEY
      - CRON_SECRET
      - WEBAPP_URL=https://forms.semudando.com.br
      - NEXTAUTH_URL=https://forms.semudando.com.br
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/formbricks?schema=public
      ############################################# OPTIONAL (EMAIL CONFIGURATION) #############################################
      # Email Configuration
      # MAIL_FROM:
      # SMTP_HOST:
      # SMTP_PORT:
      # SMTP_USER:
      # SMTP_PASSWORD:
      # SMTP_AUTHENTICATED:

      # (Additional option for TLS (port 465) only)
      # SMTP_SECURE_ENABLED:

      # If set to 0, the server will accept connections without requiring authorization from the list of supplied CAs (default is 1).
      # SMTP_REJECT_UNAUTHORIZED_TLS: 0

      ############################################## OPTIONAL (APP CONFIGURATION) ##############################################
      - EMAIL_VERIFICATION_DISABLED=1
      - PASSWORD_RESET_DISABLED=1

      # Set the below to your Unsplash API Key for their Survey Backgrounds
      # UNSPLASH_ACCESS_KEY:

volumes:
  postgres:
  uploads:
  ssh:
    external: true

configs:
  borgmatic-config-formbricks-semudando:
    external: true

networks:
  caddy:
    external: true